services:
  - type: web
    name: quizbattle-backend
    env: python
    runtime: python-3.9.18
    buildCommand: |
      python --version
      pip install --upgrade pip
      pip install -r backend/requirements.txt
    startCommand: cd backend && gunicorn run:app --bind 0.0.0.0:$PORT
    envVars:
      - key: JWT_SECRET
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: MONGO_URI
        sync: false
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 10000
      - key: PYTHON_VERSION
        value: 3.9.18
