services:
  - type: web
    name: quizbattle-backend
    env: python
    runtime: python-3.11
    region: singapore
    plan: free
    buildCommand: pip install --no-cache-dir -r backend/requirements.txt && cd backend && flask db upgrade
    startCommand: cd backend && gunicorn -w 4 -b 0.0.0.0:$PORT wsgi:app
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
      - key: FLASK_APP
        value: wsgi.py
      - key: FLASK_ENV
        value: production
      - key: JWT_SECRET
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: MONGO_URI
        sync: false
